### ISSUE TITLE
Change postgresql default port

### ISSUE THREAD

**Issue by Xevimacia** [tiangolo/full-stack-fastapi-template#329]
We are working with this template for a while. And we are now bringing it into production.
We are deploying our code based on this template in Alibaba Cloud so we will be using the ApsaraDB RDS for PostgreSQL. For security reasons, we would like to change the default port from 5432 to another port. We have tried to set the environment variable `$POSTGRES_PORT` but the variable is ignored.
Can anyone point us how to customize the postgres port?

**Comment by roura356a** [comment]
We are having the same issue here. We need to be able to change the default port. It would be nice to implement an environment variable like `POSTGRES_PORT` or something like that as mentioned above.

**Comment by tiangolo** [comment]
Thanks! This was solved here: https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/333
