### ISSUE TITLE
Fastui with sqlmodel

### ISSUE THREAD

**Issue by auh83** [tiangolo/full-stack-fastapi-template#568]
Hi @tiangolo !
Any chance to see FastUI landing to you template?

_Originally posted by @VivienGiraud in https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/541#issuecomment-1855412342_

Is there anyone to try Fastui with sqlmodel here ?

**Comment by Lymah123** [comment]
Hi, @tiangolo , @jcaguirre89 has anyone started working on this issue?

**Comment by auh83** [comment]
> Hi, @tiangolo , @jcaguirre89 has anyone started working on this issue?

Yes, @bugbytes-io statrted working on it : https://github.com/bugbytes-io/fastui-sqlmodel-demo

**Comment by TheRealBecks** [comment]
Any updates on this topic? :smiley:

**Comment by tiangolo** [comment]
Hey there! Please create a new discussion question filling the template to understand better your use case. 🤓

For now I'll close this issue.
