### ISSUE TITLE
> ## Description

### ISSUE THREAD

**Issue by zuzanabi** [tiangolo/full-stack-fastapi-template#579]
> ## Description
> 
> This is a tentative roadmap, I will update it as things evolve. Some things might be discarded, others might be added later. I didn't want to make it fully public as it could raise expectations, but it seems it would be more beneficial for the community to know all the ideas and objectives.
> 
> Work on this is alternated (and sometimes mixed) with work on FastAPI, Typer, SQLModel, Asyncer, and others.
> 
> In fact, I created SQLModel for this project. 🚀
> 
> Answering questions, issues, and PRs is also intermixed with this, but as in some cases one of these features would solve several issues or questions, or potentially solve something done by one or more PRs, in many cases I focus on this a bit more than on answering specific issues, questions, PRs.
> ## Maintenance
> 
> The word "maintenance" or "maintainer" doesn't have a very strict definition, and it probably varies a lot from perspective.
> 
> A lot of the work related to maintaining FastAPI is done by contributors by answering questions, reviewing PRs, etc.
> 
> You can help me ensure each existing PR is in shape (has tests, solves the problem, etc.). Make sure you filter out the translation PRs (most of them) unless you speak the language and can review them.
> ## Security
> 
> When there are security issues, those are handled with the highest priority. Those are normally not handled in issues and PRs but in emails, it's not public until the security disclosure is made, in most cases (always, up to now) with the version that fixes them.
> ## Roadmap
> 
> Now, here's the current high-level tentative roadmap:
> 
>     * [ ]  Upgrade to the latest FastAPI.
> 
>     * [ ]  Migration from SQLAlchemy to SQLModel.
> 
>     * [ ]  Upgrade to Pydantic v2.
> 
>     * [ ]  Refactor and simplification of most of the code, a lot of the complexity won't be necessary anymore.
> 
>     * [ ]  Migrate from Vue.js 2 to React with hooks and TypeScript.
> 
>     * [ ]  Move from Docker Swarm Model to Kubernetes.
> 
>     * [ ]  GitHub Actions for CI.
> 
> 
> All this is intermixed with reviews for PRs, issues, and discussions.

_Originally posted by @zuzanabi in https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/541#issuecomment-1880284019_

**Comment by zuzanabi** [comment]
> ```
>           > ## Description
> ```
> 
> > This is a tentative roadmap, I will update it as things evolve. Some things might be discarded, others might be added later. I didn't want to make it fully public as it could raise expectations, but it seems it would be more beneficial for the community to know all the ideas and objectives.
> > Work on this is alternated (and sometimes mixed) with work on FastAPI, Typer, SQLModel, Asyncer, and others.
> > In fact, I created SQLModel for this project. 🚀
> > Answering questions, issues, and PRs is also intermixed with this, but as in some cases one of these features would solve several issues or questions, or potentially solve something done by one or more PRs, in many cases I focus on this a bit more than on answering specific issues, questions, PRs.
> > ## Maintenance
> > The word "maintenance" or "maintainer" doesn't have a very strict definition, and it probably varies a lot from perspective.
> > A lot of the work related to maintaining FastAPI is done by contributors by answering questions, reviewing PRs, etc.
> > You can help me ensure each existing PR is in shape (has tests, solves the problem, etc.). Make sure you filter out the translation PRs (most of them) unless you speak the language and can review them.
> > ## Security
> > When there are security issues, those are handled with the highest priority. Those are normally not handled in issues and PRs but in emails, it's not public until the security disclosure is made, in most cases (always, up to now) with the version that fixes them.
> > ## Roadmap
> > Now, here's the current high-level tentative roadmap:
> > ```
> > * [ ]  Upgrade to the latest FastAPI.
> > 
> > * [ ]  Migration from SQLAlchemy to SQLModel.
> > 
> > * [ ]  Upgrade to Pydantic v2.
> > 
> > * [ ]  Refactor and simplification of most of the code, a lot of the complexity won't be necessary anymore.
> > 
> > * [ ]  Migrate from Vue.js 2 to React with hooks and TypeScript.
> > 
> > * [ ]  Move from Docker Swarm Model to Kubernetes.
> > 
> > * [ ]  GitHub Actions for CI.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All this is intermixed with reviews for PRs, issues, and discussions.
> 
> _Originally posted by @zuzanabi in [#541 (comment)](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/541#issuecomment-1880284019)_

**Comment by codespearhead** [comment]
It seems that this issue was created by mistake. Can you please close it?
