### ISSUE TITLE
Login error in Dashboard

### ISSUE THREAD

**Issue by lxbxinwei** [tiangolo/full-stack-fastapi-template#723]
Hello, @tiangolo 

I follow all steps in [full-stack-fastapi-template (latest)](https://github.com/tiangolo/full-stack-fastapi-template/tree/master)，the code run in a remote machine, and I login from another machine. 

The problem is, I can go to `ip:8090`, `ip:8080`, `ip/docs`, `ip/redoc`. However, I can not go to `ip`, the main page of the project. After I enter email and password, it just circle all the time, did not forward.

Is there anything I did wrong?

Best regards.

<img width="241" alt="Snipaste_2024-03-15_16-29-44" src="https://github.com/tiangolo/full-stack-fastapi-template/assets/138550108/68303ec1-2e8e-496e-b3d3-eba61d10151b">

**Comment by SaurabhXRT** [comment]
Could you please describe the error message you're seeing in the terminal or any other location? Providing details about the error will help in diagnosing and resolving the issue effectively.

**Comment by parthjoshi90** [comment]
I have got the same issue while running it in the local environment.

![Screenshot from 2024-03-16 12-59-32](https://github.com/tiangolo/full-stack-fastapi-template/assets/18608298/9bca5e21-5642-4e3c-af8d-e8edb65402cf)

**Comment by lxbxinwei** [comment]
> Could you please describe the error message you're seeing in the terminal or any other location? Providing details about the error will help in diagnosing and resolving the issue effectively.

I think I know the problem, but I have no idea to fix it.

When I try login on the server side, via `localhost`, everything works well.

If I login on the remote device via `ip`, it can not work.

and the error in console(remote device) is👇 (look at the red box)
![Pasted image 20240318094806](https://github.com/tiangolo/full-stack-fastapi-template/assets/138550108/d9e8390c-6c86-472c-9390-ee5fbc31b1e1)

**Comment by lxbworld** [comment]
> I have got the same issue while running it in the local environment.
> 
> ![Screenshot from 2024-03-16 12-59-32](https://private-user-images.githubusercontent.com/18608298/313385456-9bca5e21-5642-4e3c-af8d-e8edb65402cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTI3NDcsIm5iZiI6MTcxMDg1MjQ0NywicGF0aCI6Ii8xODYwODI5OC8zMTMzODU0NTYtOWJjYTVlMjEtNTY0Mi00ZTNjLWFmOGQtZThlZGI2NTQwMmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEyNDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MDc3ODE4NTE2YjUzNjA3ZTliMzIyZjQxMmY5ZWI1ZjhkYmM1OWMwNzUzOGI5ZjQyYTI0NGI1ZTRkNWRlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.30np2G92KSumz3Q2PEiN0XSWfBVl_o-gHswKCY_L6Fs)

same as you

**Comment by lxbxinwei** [comment]
I delete the frontend images, and `docker compose -f docker-compose.yml up -d` again, everything works

**Comment by tiangolo** [comment]
Thanks for reporting back!
